// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleFleetManagement.Data;

#nullable disable

namespace VehicleFleetManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221229195800_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VehicleFleetManagement.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acura"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Buick"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cadillac"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chrysler"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Citroen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cupra"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dacia"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Daewoo"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 17,
                            Name = "DS Automobiles"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 21,
                            Name = "GMC"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Holden"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hummer"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Infiniti"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Isuzu"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Koenigsegg"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Lada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Lancia"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Lincoln"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Lotus"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Maserati"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Maybach"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 42,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Pagani"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Pontiac"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Rimac"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Saab"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Saleen"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Scion"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Seat"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Škoda"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Vauxhall"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("VehicleFleetManagement.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "CDX"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "ILX"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "MDX"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Name = "NSX"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Name = "RDX"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 2,
                            Name = "Giulia"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 2,
                            Name = "Giulietta"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 2,
                            Name = "Stelvio"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 2,
                            Name = "Tonale"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 2,
                            Name = "146"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 2,
                            Name = "147"
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 3,
                            Name = "DB11"
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 3,
                            Name = "DBS Superleggera"
                        },
                        new
                        {
                            Id = 56,
                            BrandId = 3,
                            Name = "DBX"
                        },
                        new
                        {
                            Id = 57,
                            BrandId = 3,
                            Name = "V12 Vantage"
                        },
                        new
                        {
                            Id = 58,
                            BrandId = 3,
                            Name = "Valkyrie"
                        },
                        new
                        {
                            Id = 80,
                            BrandId = 4,
                            Name = "A1"
                        },
                        new
                        {
                            Id = 81,
                            BrandId = 4,
                            Name = "A1 citycarver"
                        },
                        new
                        {
                            Id = 82,
                            BrandId = 4,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 83,
                            BrandId = 4,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 84,
                            BrandId = 4,
                            Name = "A4 Allroad"
                        },
                        new
                        {
                            Id = 85,
                            BrandId = 4,
                            Name = "A5"
                        },
                        new
                        {
                            Id = 86,
                            BrandId = 4,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 87,
                            BrandId = 4,
                            Name = "A6 Allroad"
                        },
                        new
                        {
                            Id = 101,
                            BrandId = 4,
                            Name = "Q8"
                        },
                        new
                        {
                            Id = 102,
                            BrandId = 4,
                            Name = "R8"
                        },
                        new
                        {
                            Id = 103,
                            BrandId = 4,
                            Name = "RS e-tron GT"
                        },
                        new
                        {
                            Id = 104,
                            BrandId = 4,
                            Name = "RS Q3"
                        },
                        new
                        {
                            Id = 105,
                            BrandId = 4,
                            Name = "RS Q3 Sportback"
                        },
                        new
                        {
                            Id = 106,
                            BrandId = 4,
                            Name = "RS Q8"
                        },
                        new
                        {
                            Id = 107,
                            BrandId = 4,
                            Name = "RS3"
                        },
                        new
                        {
                            Id = 108,
                            BrandId = 4,
                            Name = "RS4"
                        },
                        new
                        {
                            Id = 109,
                            BrandId = 4,
                            Name = "RS5"
                        },
                        new
                        {
                            Id = 110,
                            BrandId = 4,
                            Name = "RS6"
                        },
                        new
                        {
                            Id = 111,
                            BrandId = 4,
                            Name = "RS7"
                        },
                        new
                        {
                            Id = 112,
                            BrandId = 4,
                            Name = "S3"
                        },
                        new
                        {
                            Id = 113,
                            BrandId = 4,
                            Name = "S4"
                        },
                        new
                        {
                            Id = 114,
                            BrandId = 4,
                            Name = "S5"
                        },
                        new
                        {
                            Id = 115,
                            BrandId = 4,
                            Name = "S6"
                        },
                        new
                        {
                            Id = 116,
                            BrandId = 4,
                            Name = "S7"
                        },
                        new
                        {
                            Id = 117,
                            BrandId = 4,
                            Name = "S8"
                        },
                        new
                        {
                            Id = 118,
                            BrandId = 4,
                            Name = "SQ2"
                        },
                        new
                        {
                            Id = 119,
                            BrandId = 4,
                            Name = "SQ5"
                        },
                        new
                        {
                            Id = 120,
                            BrandId = 4,
                            Name = "SQ5 Sportback"
                        },
                        new
                        {
                            Id = 121,
                            BrandId = 4,
                            Name = "SQ7"
                        },
                        new
                        {
                            Id = 122,
                            BrandId = 4,
                            Name = "SQ8"
                        },
                        new
                        {
                            Id = 123,
                            BrandId = 4,
                            Name = "TT"
                        },
                        new
                        {
                            Id = 124,
                            BrandId = 4,
                            Name = "TT RS"
                        },
                        new
                        {
                            Id = 125,
                            BrandId = 4,
                            Name = "TT S"
                        },
                        new
                        {
                            Id = 126,
                            BrandId = 4,
                            Name = "100"
                        },
                        new
                        {
                            Id = 127,
                            BrandId = 4,
                            Name = "200"
                        },
                        new
                        {
                            Id = 128,
                            BrandId = 4,
                            Name = "4000"
                        },
                        new
                        {
                            Id = 129,
                            BrandId = 4,
                            Name = "5+5"
                        },
                        new
                        {
                            Id = 130,
                            BrandId = 4,
                            Name = "5000"
                        },
                        new
                        {
                            Id = 131,
                            BrandId = 4,
                            Name = "80"
                        },
                        new
                        {
                            Id = 132,
                            BrandId = 4,
                            Name = "90"
                        },
                        new
                        {
                            Id = 133,
                            BrandId = 4,
                            Name = "A2"
                        },
                        new
                        {
                            Id = 134,
                            BrandId = 4,
                            Name = "Allroad"
                        },
                        new
                        {
                            Id = 135,
                            BrandId = 4,
                            Name = "Cabriolet"
                        },
                        new
                        {
                            Id = 136,
                            BrandId = 4,
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 137,
                            BrandId = 4,
                            Name = "RS2"
                        },
                        new
                        {
                            Id = 138,
                            BrandId = 4,
                            Name = "S1"
                        },
                        new
                        {
                            Id = 139,
                            BrandId = 4,
                            Name = "S2"
                        },
                        new
                        {
                            Id = 140,
                            BrandId = 4,
                            Name = "V8"
                        });
                });

            modelBuilder.Entity("VehicleFleetManagement.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EnginPower")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpRegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("VehicleWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnginPower = 265,
                            ExpRegDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelId = 3,
                            Registration = "A08-I-415",
                            Seats = 7,
                            VehicleWeight = 1600
                        },
                        new
                        {
                            Id = 2,
                            EnginPower = 375,
                            ExpRegDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelId = 25,
                            Registration = "A68-E-425",
                            Seats = 5,
                            VehicleWeight = 1450
                        },
                        new
                        {
                            Id = 3,
                            EnginPower = 309,
                            ExpRegDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelId = 83,
                            Registration = "M55-A-405",
                            Seats = 5,
                            VehicleWeight = 1575
                        },
                        new
                        {
                            Id = 5,
                            EnginPower = 309,
                            ExpRegDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelId = 3,
                            Registration = "M21-E-452",
                            Seats = 5,
                            VehicleWeight = 1575
                        },
                        new
                        {
                            Id = 6,
                            EnginPower = 125,
                            ExpRegDate = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelId = 3,
                            Registration = "M33-K-217",
                            Seats = 5,
                            VehicleWeight = 1475
                        });
                });

            modelBuilder.Entity("VehicleFleetManagement.Models.Model", b =>
                {
                    b.HasOne("VehicleFleetManagement.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleFleetManagement.Models.Vehicle", null)
                        .WithMany("Models")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("VehicleFleetManagement.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VehicleFleetManagement.Models.Vehicle", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
